### ISSUE TITLE
Created 1 groups of sizes 0. 

### ISSUE THREAD

**Issue by jimr1603** [hoehleatsu/socialroulette#5]
Whenever I use MDGP algorithm I get a null result - the pairings list is `[[1]] character(0)`, and the system message is "Created 1 groups of sizes 0". 

The quickest way I have to reproduce the bug is the example code at https://hoehleatsu.github.io/socialroulette/index.html .

**Comment by mhoehle** [comment]
Your PR #6 seemed to fix the problem on my machine

    R version 4.1.1 (2021-08-10)
    Platform: x86_64-apple-darwin17.0 (64-bit)
    Running under: macOS Big Sur 10.16

Thanks for pointing out the problem and providing a solution alongside.

**Comment by mhoehle** [comment]
Fixed by PR #6.
